#!/bin/sh
set -e

install -d -m 755 "/etc/hysteria/client"
install -d -m 755 "/etc/hysteria/server"

ln -fs "/opt/lib/systemd/system/hysteria-client@.service" "/etc/systemd/system/hysteria-client@.service"
ln -fs "/opt/lib/systemd/system/hysteria-server@.service" "/etc/systemd/system/hysteria-server@.service"

if [ -d "/run/systemd/system" ]
then
	systemctl daemon-reload
fi
