name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check Package Version
    runs-on: ubuntu-slim
    outputs:
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
      - name: Setup Debian Packaging Environment
        run: |
          sudo apt-get update
          sudo apt-get install -qy --no-install-recommends \
            python3-debian
      - id: check
        name: Check Package Version
        run: |
          import os, sys
          from debian import deb822
          from debian.debian_support import Version

          try:
            with open('debian/DEBIAN/control', 'r') as file:
              control = deb822.Deb822(file)

            version = control.get('Version', '0.0.0')

            if not (Version(version) > Version('0.0.0')):
              print(
                f"::error file=debian/DEBIAN/control,title=Version Error::Invalid version {version}",
                file=sys.stderr
              )
              sys.exit(0)

            with open(os.environ['GITHUB_OUTPUT'], 'a') as file:
              print(f"version={version}", file=file)
          except Exception as error:
            print(f"::error::Parse failed: {error}", file=sys.stderr)
            sys.exit(1)
        shell: python

  build:
    name: Build Package
    needs: check
    if: needs.check.outputs.version != ''
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: src/go.work
          cache-dependency-path: src/go.work.sum
      - name: Build Hysteria
        run: |
          python hyperbole.py build -r

          if [[ ! -f build/hysteria-linux-arm64 ]]
          then
            printf "::error file=src/build/hysteria-linux-arm64::'hysteria-linux-arm64' not found.\n" >&2
            exit 1
          fi
        working-directory: src
      - name: Build Debian Package
        run: |
          install -Ds src/build/hysteria-linux-arm64 debian/opt/bin/hysteria

          dpkg-deb -z 9 -Z xz --root-owner-group -b debian .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unifi-hysteria_${{ needs.check.outputs.version }}_arm64.deb
          path: unifi-hysteria_${{ needs.check.outputs.version }}_arm64.deb

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
      - check
    runs-on: ubuntu-slim
    steps:
      - id: artifact
        name: Download Artifact
        uses: actions/download-artifact@v8
      - name: Release
        run: |
          gh release create "${{ needs.check.outputs.version }}" \
            "${{ steps.artifact.outputs.download-path }}/unifi-hysteria_${{ needs.check.outputs.version }}_arm64.deb" \
            -R "${{ github.repository }}" \
            --target ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
